version: "3"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - thanos


  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    restart: always
    networks:
      - thanos


  eating-an-elefant-app:
    build: .
    environment:
      NATS_URL: "nats://nats:4222"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://elephant:onebiteatatime@timescaledb:5432/elephantdatabase"
      POSTGRES_HOST: "timescaledb"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "elephant"
      POSTGRES_PASSWORD: "onebiteatatime"
      POSTGRES_DB: "elephantdatabase"
    ports:
      - "5000:5000"
    networks:
      - thanos
  
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_PASSWORD: onebiteatatime
      POSTGRES_USER: elephant
      POSTGRES_DB: elephantdatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
    - thanos


  thanos:
    image: thanosio/thanos:v0.22.0
    # command: sidecar --prometheus.url=http://prometheus:9090
    command:
      - sidecar
      - --prometheus.url=http://prometheus:9090
      - --grpc-address=0.0.0.0:19091
      - --http-address=0.0.0.0:19092
    ports:
      - "19091:19091"
    volumes:
      - thanos:/data
    networks:
      - thanos

  prometheus:
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    networks:
      - thanos
    environment:
      - "GLOBAL__external_labels=cluster=my-cluster-name,environment=production"
      
    volumes:
      - ./prometheus_edit.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  thanos-query:
    image: thanosio/thanos:v0.22.0
    command:
      - query
      - --grpc-address=0.0.0.0:19191
      - --http-address=0.0.0.0:19192
      - --query.replica-label=prometheus_replica
      - --store=thanos:19091
    ports:
      - "19191:19191"
      - "19192:19192"
    networks:
      - thanos


  grafana:
    image: grafana/grafana:8.2.6
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - thanos
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://elephant:onebiteatatime@timescaledb:5432/elephantdatabase"


    command:
      - "-config=/etc/grafana/grafana.ini"


networks:
  thanos: {}

  

volumes:
  thanos: {}
  timescaledb_data: {}
  grafana_data: {}