version: "3"
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
  prometheus-nats-exporter:
    build: .
    image: prometheus-nats-exporter
    ports:
      - "7777:7777"
  eating-an-elefant-app:
    build: .
    ports:
      - "5000:5000"
