global:
  scrape_interval: 10s
  external_labels:
    cluster: elephant-cluster
    environment: development

scrape_configs:
  - job_name: "nats_kiosk_data"
    static_configs:
      - targets: ["pushgateway:9091"]